[tool.poetry]
name = "monty-hall-simulator"
version = "0.1.0"
description = ""
authors = ["Andrea Del Corto <andrea.delcorto@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
